name: Deploy to GitHub Pages

# main ブランチへ push されたときにトリガー
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - uses: actions/checkout@v3

      # 2. Node.js をセットアップ（バージョンはプロジェクトに合わせて）
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      # 3. 依存のインストール
      - name: Install dependencies
        run: npm install

      # 4. ビルド（npm run build でも yarn build でも）
      - name: Build
        run: npm run build

      # 5. 成果物を gh-pages ブランチにデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # build スクリプトで出力したフォルダ名
          publish_dir: ./dist
